version: '3'

services:
  websocket:
    container_name: restream.websocket
    build: .
    command: ./server
    ports:
      - "3000:3000"
    restart: always
    networks:
      - network

networks:
  network:
    driver: bridge