version: '3'

services:
  websocket:
    container_name: restream.websocket
    build: .
    command: ./server
    restart: always
    volumes:
      - restreamweb_sockets:/restream.app/sockets
    networks:
      - default

networks:
  default:
    external:
      name: restreamweb_network

volumes:
  restreamweb_sockets:
    external: true