version: '3'

services:
  websocket:
    container_name: restream.websocket
    build: .
    command: ./server
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - cdn:/restream.app/static
      - sockets:/restream.app/sockets
    networks:
      - default

networks:
  default:
    external:
      name: restreamweb_network

volumes:
    cdn:
    sockets: